# Generated by Django 4.0.4 on 2022-05-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=16)),
                ('room_description', models.CharField(max_length=200)),
                ('room_state', models.CharField(default='---------', max_length=9)),
            ],
        ),
    ]
